// Legal glossary of common Indian legal terms with plain-English definitions
export const legalGlossary = {
  "IPC": "Indian Penal Code — the main criminal code of India, enacted in 1860.",
  "CrPC": "Code of Criminal Procedure — the procedural law for criminal trials in India.",
  "FIR": "First Information Report — a written document filed with police to report a cognizable offence.",
  "Cognizable": "An offence for which police can arrest without a warrant and investigate without court permission.",
  "Non-cognizable": "An offence where police cannot arrest or investigate without a magistrate's order.",
  "Bailable": "An offence where the accused has a right to be released on bail.",
  "Non-bailable": "An offence where bail is not a right and must be granted by a court.",
  "Writ": "A formal written order from a court commanding a party to do or refrain from doing something.",
  "Habeas Corpus": "A writ requiring a person under arrest to be brought before a judge; used to protect against unlawful detention.",
  "Mandamus": "A writ ordering a public authority to perform a legal duty it has failed to do.",
  "RTI": "Right to Information — a law enabling citizens to request information from public authorities.",
  "PIL": "Public Interest Litigation — a petition filed in court for the protection of public interest.",
  "Affidavit": "A written statement confirmed by oath, used as evidence in court proceedings.",
  "Injunction": "A court order requiring a party to do or stop doing a specific action.",
  "Acquittal": "A formal judgment that the accused is not guilty of the charges.",
  "Bail": "Temporary release of an accused person awaiting trial, subject to conditions.",
  "Anticipatory Bail": "Bail granted in anticipation of arrest under Section 438 of the CrPC.",
  "Chargesheet": "A formal document filed by police presenting the charges against an accused person.",
  "Magistrate": "A judicial officer who deals with minor criminal cases and preliminary hearings.",
  "Sessions Court": "A district-level court that handles serious criminal cases like murder and robbery.",
  "High Court": "The highest court of a state, which hears appeals from lower courts.",
  "Supreme Court": "The apex court of India, with final appellate jurisdiction over all courts.",
  "Summons": "A legal document ordering a person to appear before a court.",
  "Warrant": "A document issued by a court authorising police to arrest a person or search a premise.",
  "Ex-parte": "A decision made by a court hearing only one side of a case.",
  "Stay Order": "A court order temporarily halting a proceeding or enforcement of a judgment.",
  "POCSO": "Protection of Children from Sexual Offences Act — law protecting children from sexual abuse.",
  "Dowry": "Property or money brought by a bride to her husband on their marriage.",
  "Arbitration": "A method of dispute resolution outside of courts, decided by an arbitrator.",
  "Caveat": "A legal notice filed to ensure one is heard before a court passes an order.",
};
